# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up docker env
      run: docker compose -f docker-compose.test.yml up --build -d
      working-directory: app

    - name: DB migrations
      run: docker compose -f docker-compose.test.yml exec test-express-app npx prisma migrate dev --name init
      working-directory: app    

    - name: Generate prisma client
      run: docker compose -f docker-compose.test.yml exec test-express-app npx prisma generate
      working-directory: app

    - name: run tests
      run: docker compose -f docker-compose.test.yml exec test-express-app npm run test
      working-directory: app